### ISSUE TITLE
Plugin documentation / help

### ISSUE THREAD

**Issue by cmnord** [botopolis/bot#21]
It would be nice if there was an easy way for plugin implementers to include a list of available commands, description of what they do, etc. that bot users can access via `bot help` or `bot help <plugin>`.

Similar: [hubot-help](https://github.com/hubotio/hubot-help) parses comments.

**Comment by berfarah** [comment]
Addressed here: https://github.com/botopolis/bot/pull/22, thanks for the suggestion!
